global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: immich_api
    static_configs:
      - targets: ['immich-server:8081']

  - job_name: immich_microservices
    static_configs:
      - targets: ['immich-server:8082']

  - job_name: sticker_serving
    static_configs:
      - targets: ['172.17.0.1:8004']
    metrics_path: /metrics

  - job_name: sticker_dummy_api
    static_configs:
      - targets: ['172.17.0.1:8000']
    metrics_path: /metrics
